Completed es6-operators exercise
hollyphung95/m2-0723-code-solutions pull request #6
Opened 2023-07-20 10:42 UTC by hollyphung95

<img width="1000" alt="Screenshot 2023-07-20 at 3 39 05 AM" src="https://github.com/hollyphung95/m2-0723-code-solutions/assets/59667095/d52c43f6-c1e0-4b76-ace3-0fcc9f763743">

2023-07-21 03:39 UTC, TimelikeClosure requested changes

2023-07-21 03:39 UTC, TimelikeClosure commented on es6-operators/main.js
> +if (v2) console.log('v2 is truthy');
Try accomplishing these with logical ANDs

2023-08-01 20:53 UTC, hollyphung95 commented on es6-operators/main.js
> +if (v2) console.log('v2 is truthy');
<img width="1500" alt="Screenshot 2023-08-01 at 1 49 34 PM" src="https://github.com/hollyphung95/m2-0723-code-solutions/assets/59667095/e2273888-a4c6-4815-a199-852d64368028">

2023-08-02 01:34 UTC, TimelikeClosure approved these changes

2023-08-06 08:33 UTC, merged