completed array-methods exercise
hollyphung95/m2-0723-code-solutions pull request #7
Opened 2023-07-21 01:40 UTC by hollyphung95

![Kapture 2023-07-20 at 18 33 39](https://github.com/hollyphung95/m2-0723-code-solutions/assets/59667095/b19bd486-ea07-4c13-b2dd-d4a84a26639b)

2023-07-21 04:00 UTC, TimelikeClosure requested changes

2023-07-21 04:00 UTC, TimelikeClosure commented on array-methods/for-each.js
> +});
While this is a valid way to create a reversed array with `.forEach`, try logging the values in reverse order _without_ creating a new array, using just the parameters passed to the `.forEach` callback function.

2023-07-21 04:00 UTC, TimelikeClosure commented on array-methods/map.js
> +}));
Nice approach, but notice that the price objects should still contain numbers, not formatted strings:

---

![image](https://github.com/hollyphung95/m2-0723-code-solutions/assets/16143771/fa325a39-fb6e-4130-9a99-4d25d90033f9)

2023-08-01 20:29 UTC, hollyphung95 commented on array-methods/map.js
> +}));
<img width="535" alt="Screenshot 2023-08-01 at 1 25 32 PM" src="https://github.com/hollyphung95/m2-0723-code-solutions/assets/59667095/4e473a20-24b8-4d58-888c-cea95a4ac69a">

2023-08-02 01:36 UTC, TimelikeClosure approved these changes

2023-08-06 08:35 UTC, merged